// <auto-generated />
namespace MunicipalTrashCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedALotOfShit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedALotOfShit));
        
        string IMigrationMetadata.Id
        {
            get { return "201610221930239_AddedALotOfShit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
